### ISSUE TITLE
Tracking issue for incomplete essential parts

### ISSUE THREAD

**Issue by DanShaders** [DanShaders/kege-by-danshaders#17]
- [x] user participation interface
- [ ] development & deployment script
- [ ] task import from kompege.ru
- [ ] task import from pdf source
- [x] creation of kim from tasks
- [x] task filters
- [x] standings
- [x] kim settings
- [ ] active sessions management
- [ ] user management
- [ ] user filters
- [ ] user import
- [ ] group management
